name: BUILD CI
  
on:
  workflow_dispatch:
    inputs:
      DEPLOY_TYPE:
        description: 'Deploy Type (TEST/DEBUG)'
        required: true
        default: 'DEBUG'
      ChangeLogs:
        description: 'Build ChangeLogs'
        required: true
        default: 'Misc changes'
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: d8 to dx
      run: |
         (cd /usr/local/lib/android/sdk/build-tools/33.0.0 \
         && mv d8 dx \
         && cd lib  \
         && mv d8.jar dx.jar)
    - name: Integrate dos2unix
      run: |
         sudo apt-get install dos2unix
         dos2unix ./gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build apk with Gradle
      run: ./gradlew clean assemble
    - name: Upload apk to Telegram
      run: |
         message="Floating Volume debug build is up for testing"
         curl -F chat_id="-1001379101256" -F document=@"app/build/outputs/apk/debug/app-debug.apk" -F caption="$message $time" https://api.telegram.org/bot1822006486:AAGX5JWqloJdIin7XbhjtVSsFWb06B3Uk1w/sendDocument
